# .travis.yaml
language: python
sudo: true

cache:
  pip: true
  directories:
  - lua_install

env:
  - LUA="lua=5.1"

before_install:
  # install lua
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - build/install.sh

before_script:
  - cd test

script:
  - busted_bootstrap --pattern=2_.+_.+%.lua --verbose .
