# .travis.yaml
language: python
sudo: true

cache:
  pip: true
  directories:
  - lua_install

env:
  - LUA="lua=5.1"

install:
  - build/install.sh

before_script:
  - cd test

script:
  - busted_bootstrap --pattern=2_.+_.+%.lua --verbose .
