# .travis.yaml
language: python
sudo: false

env:
  - LUA="lua=5.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks install busted
  - luarocks install luv

script:
  - busted --verbose test